# Generated by Django 3.2.15 on 2022-09-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
